#include "tpm/Lock.h"

#define TOML_EXCEPTIONS 0
#include <toml++/toml.hpp>

#include <filesystem>
#include <sstream>

namespace fs = std::filesystem;

namespace tpm {

std::optional<Lock> Lock::load(const std::string& path, bool& exists,
                               std::string& error) {
    exists = fs::exists(path);
    if (!exists) return Lock{}; // absent lock == empty graph, not an error

    toml::parse_result result = toml::parse_file(path);
    if (!result) {
        std::ostringstream os;
        os << "failed to parse " << path << ": " << result.error().description();
        error = os.str();
        return std::nullopt;
    }
    const toml::table& tbl = result.table();

    Lock lock;
    auto str = [](const toml::table& t, const char* key) -> std::string {
        if (auto v = t[key].value<std::string>()) return *v;
        return "";
    };

    if (const toml::array* arr = tbl["package"].as_array()) {
        for (const auto& el : *arr) {
            const toml::table* pt = el.as_table();
            if (!pt) {
                error = "tpm.lock: [[package]] entry must be a table";
                return std::nullopt;
            }
            LockedPackage lp;
            lp.name = str(*pt, "name");
            lp.version = str(*pt, "version");
            lp.source = str(*pt, "source");
            lp.revision = str(*pt, "revision");
            lp.contentHash = str(*pt, "content_hash");
            if (lp.name.empty()) {
                error = "tpm.lock: a [[package]] entry is missing 'name'";
                return std::nullopt;
            }
            lock.packages.push_back(std::move(lp));
        }
    }
    return lock;
}

std::string Lock::toToml() const {
    std::ostringstream os;
    os << "# tpm.lock — generated by tpm; do not edit by hand.\n";
    os << "# Pins the fully-resolved dependency graph.\n";
    for (const auto& p : packages) {
        os << "\n[[package]]\n";
        os << "name = \"" << p.name << "\"\n";
        os << "version = \"" << p.version << "\"\n";
        os << "source = \"" << p.source << "\"\n";
        os << "revision = \"" << p.revision << "\"\n";
        os << "content_hash = \"" << p.contentHash << "\"\n";
    }
    return os.str();
}

const LockedPackage* Lock::find(const std::string& name) const {
    for (const auto& p : packages)
        if (p.name == name) return &p;
    return nullptr;
}

} // namespace tpm
