#include "tpm/Lock.h"

#define TOML_EXCEPTIONS 0
#include <toml++/toml.hpp>

#include <filesystem>
#include <sstream>

namespace fs = std::filesystem;

namespace tpm {

std::optional<Lock> Lock::load(const std::string& path, bool& exists,
                               std::string& error) {
    exists = fs::exists(path);
    if (!exists) return Lock{}; // absent lock == empty graph, not an error

    toml::parse_result result = toml::parse_file(path);
    if (!result) {
        std::ostringstream os;
        os << "failed to parse " << path << ": " << result.error().description();
        error = os.str();
        return std::nullopt;
    }
    const toml::table& tbl = result.table();

    Lock lock;
    auto str = [](const toml::table& t, const char* key) -> std::string {
        if (auto v = t[key].value<std::string>()) return *v;
        return "";
    };

    if (const toml::array* arr = tbl["package"].as_array()) {
        for (const auto& el : *arr) {
            const toml::table* pt = el.as_table();
            if (!pt) {
                error = "tpm.lock: [[package]] entry must be a table";
                return std::nullopt;
            }
            LockedPackage lp;
            lp.name = str(*pt, "name");
            lp.version = str(*pt, "version");
            lp.source = str(*pt, "source");
            lp.revision = str(*pt, "revision");
            lp.contentHash = str(*pt, "content_hash");
            if (lp.name.empty()) {
                error = "tpm.lock: a [[package]] entry is missing 'name'";
                return std::nullopt;
            }
            lock.packages.push_back(std::move(lp));
        }
    }

    // A tpm.lock is generated, never hand-edited; a name/version carrying a
    // path separator or `..` is a tampered file and MUST NOT be allowed to
    // compose a cache destination that escapes `.topo-pkgs/`. This mirrors
    // Manifest::validate()'s path-traversal defence on the lock surface,
    // which feeds the same cache.packageDir(...) -> fs::remove_all path.
    auto problems = lock.validate();
    if (!problems.empty()) {
        error = "tpm.lock: " + problems.front();
        return std::nullopt;
    }
    return lock;
}

std::vector<std::string> Lock::validate() const {
    std::vector<std::string> problems;
    auto reject = [&](const std::string& pkg, const char* what,
                      const std::string& value, const char* why) {
        problems.push_back(std::string("[[package]] '") + pkg + "' " + what +
                           " '" + value + "' " + why +
                           "; path-traversal payload rejected");
    };
    for (const auto& p : packages) {
        // version composes the leaf cache directory and must contain NO path
        // separator at all (mirrors Manifest::validate()'s version guard).
        if (p.version.find('/') != std::string::npos ||
            p.version.find('\\') != std::string::npos)
            reject(p.name, "version", p.version, "contains a path separator");
        if (p.version.find("..") != std::string::npos)
            reject(p.name, "version", p.version, "contains '..'");

        // name is the `<namespace>/<name>` coordinate and legitimately holds
        // a single forward slash, so a bare `/` is allowed — but a backslash,
        // a `..` segment, or a leading separator (which would reset the cache
        // join to an absolute path) all escape the cache root and are
        // rejected.
        if (!p.name.empty() && (p.name.front() == '/' || p.name.front() == '\\'))
            reject(p.name, "name", p.name, "is an absolute path");
        if (p.name.find('\\') != std::string::npos)
            reject(p.name, "name", p.name, "contains a backslash separator");
        if (p.name.find("..") != std::string::npos)
            reject(p.name, "name", p.name, "contains '..'");
    }
    return problems;
}

std::string Lock::toToml() const {
    std::ostringstream os;
    os << "# tpm.lock — generated by tpm; do not edit by hand.\n";
    os << "# Pins the fully-resolved dependency graph.\n";
    for (const auto& p : packages) {
        os << "\n[[package]]\n";
        os << "name = \"" << p.name << "\"\n";
        os << "version = \"" << p.version << "\"\n";
        os << "source = \"" << p.source << "\"\n";
        os << "revision = \"" << p.revision << "\"\n";
        os << "content_hash = \"" << p.contentHash << "\"\n";
    }
    return os.str();
}

const LockedPackage* Lock::find(const std::string& name) const {
    for (const auto& p : packages)
        if (p.name == name) return &p;
    return nullptr;
}

} // namespace tpm
